version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB="${DB_DATABASE}"
      - POSTGRES_PASSWORD="${DB_PASSWORD}"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
      
  auth-server:
    image: jedster1111/yourtune
    restart: always
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
    ports:
      - "8000:8000"