version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - "POSTGRES_DB=${DB_DATABASE}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USERNAME}"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}"

  auth-server:
    image: jedster1111/yourtune
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
    ports:
      - "8000:8000"